# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push
# event but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: python:3.8.3-alpine

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Update and install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install g++ valgrind
          poetry install

      - name: Compile code
        run: g++ hello.cpp -o hello

      - name: Run code
        run: ./hello

      - name: Run valgrind
        run: valgrind ./hello
